Web.931803.Chegodaeva.Lab4/Models/ErrorViewModel.cs
using System;

namespace Web._931803.Chegodaeva.Lab4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web.931803.Chegodaeva.Lab4/Models/PassResetModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web._931803.Chegodaeva.Lab4.Models
{
    public class PassResetModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        public string Message { get; set; }

        public string Code { get; set; }
    }
}

Web.931803.Chegodaeva.Lab4/Models/ResetModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Web._931803.Chegodaeva.Lab4.Models
{
    public class ResetModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        public string Message { get; set; }

        public string Code { get; set; }
    }
}

Web.931803.Chegodaeva.Lab4/Models/SignUpModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web._931803.Chegodaeva.Lab4.Models
{
    public class SignUpModel
    {
        [Required]
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Day { get; set; }

        public string Month { get; set; }

        public string Year { get; set; }

        public string Gender { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The password and confirm password don't match!")]
        public string Confirm { get; set; }
    }
}

Web.931803.Chegodaeva.Lab4/Controllers/ControlsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web._931803.Chegodaeva.Lab4.Controllers
{
    public class ControlsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TextBox()
        {
            ViewBag.Visible = true;
            return View();
        }

        public IActionResult TextArea()
        {
            ViewBag.Visible = true;
            return View();
        }

        public IActionResult CheckBox()
        {
            ViewBag.Visible = true;
            return View();
        }

        public IActionResult Radio()
        {
            ViewBag.Visible = true;
            return View();
        }

        public IActionResult DropDownList()
        {
            ViewBag.Visible = true;
            return View();
        }

        public IActionResult ListBox()
        {
            ViewBag.Visible = true;
            return View();
        }

        public IActionResult ControlHandler(string type, string answer)
        {
            ViewBag.Visible = false;
            if (type != "CheckBox")
                ViewBag.Answer = answer;
            else
                ViewBag.Answer = answer == null ? "false" : "true";

            return View(type);
        }
    }
}

Web.931803.Chegodaeva.Lab4/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Web._931803.Chegodaeva.Lab4.Models;

namespace Web._931803.Chegodaeva.Lab4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web.931803.Chegodaeva.Lab4/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web._931803.Chegodaeva.Lab4.Models;

namespace Web._931803.Chegodaeva.Lab4.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ResetPassFirst()
        {
            return View();
        }

        public IActionResult ResetPassFirst(ResetModel model, string action)
        {
            if (model.Code == null)
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                if (action == "Send")
                {
                    model.Message = "Check your e-mail";
                    return View("ResetPassSecond", model);
                }
                else
                {
                    model.Message = "";
                    return View("ResetPassSecond", model);
                }
            }
            else { return View("ResetPassResult"); }
        }

        [HttpGet]
        public IActionResult SignUpFirst()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUpFirst(SignUpModel model)
        {

            if (string.IsNullOrEmpty(model.FirstName))
            {
                return View("SignUpFirst");
            }
            if (model.Email == null)
            {
                return View("SignUpSecond");
            }
            else
            {
                return !ModelState.IsValid ? View("SignUpSecond") : View("SignUpResult", model);
            }
        }
    }
}

Web.931803.Chegodaeva.Lab4/Views/Controls/CheckBox.cshtml
@{
    ViewData["Title"] = "Check Box";
}

<div class="row">
    <div class="col-md-3">
        <form asp-action="ControlHandler" asp-controller="Controls">

            <input name="type" class="form-control "
                   style="display: none" value="CheckBox" />
            <h2 style="box-sizing: content-box">Check Box</h2>
            <b>IsSelected</b>
            @if (ViewBag.Visible)
            {
                <input type="checkbox" name="answer" class="form-control" />
                <br />
                <input type="submit" value="Submit" />
            }
            else
            {
                @ViewBag.Answer
            }
        </form>
    </div>
</div>

Web.931803.Chegodaeva.Lab4/Views/Controls/DropDownList.cshtml
@{
    ViewData["Title"] = "Drop-down list";
}

<div class="row">
    <div class="col-md-3">
        <form asp-action="ControlHandler" asp-controller="Controls">
            <h2>Drop-down list</h2>
            <b>Month</b>

            <input name="type" class="form-control "
                   style="display: none" value="DropDownList"/>

            @if (ViewBag.Visible)
            {
        <select name="answer" class="form-control">
            <option value="January">January</option>
            <option value="February">February</option>
            <option value="March">March</option>
            <option value="April">April</option>
            <option value="May">May</option>
            <option value="June">June</option>
            <option value="July">July</option>
            <option value="August">August</option>
            <option value="September">September</option>
            <option value="October">October</option>
            <option value="November">November</option>
            <option value="December">December</option>
        </select>
                <br />
                <input type="submit" value="Submit" />
            }
            else
            {
                @ViewBag.Answer
            }
        </form>
    </div>
</div>

Web.931803.Chegodaeva.Lab4/Views/Controls/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    
}

<div class="text-left">
    <h1>Controls</h1>

    <ul>
        <li>
            <a asp-area="" asp-controller="Controls" asp-action="Textbox">TextBox</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Controls" asp-action="TextArea">TextArea</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Controls" asp-action="CheckBox">CheckBox</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Controls" asp-action="Radio">Radio</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Controls" asp-action="DropDownList">DropDownList</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Controls" asp-action="ListBox">ListBox</a>
        </li>
    </ul>


</div>

Web.931803.Chegodaeva.Lab4/Views/Controls/ListBox.cshtml
@{
    ViewData["Title"] = "List Box";
}

<div class="row">
    <div class="col-md-3">
        <form asp-action="ControlHandler" asp-controller="Controls">
            <h2>List Box</h2>
            <b>Month</b>

            <input name="type" class="form-control "
                   style="display: none" value="ListBox"/>

            @if (ViewBag.Visible)
            {
        <select name="answer" class="form-control" size="12">
            <option value="January">January</option>
            <option value="February">February</option>
            <option value="March">March</option>
            <option value="April">April</option>
            <option value="May">May</option>
            <option value="June">June</option>
            <option value="July">July</option>
            <option value="August">August</option>
            <option value="September">September</option>
            <option value="October">October</option>
            <option value="November">November</option>
            <option value="December">December</option>
        </select>
                <br />
                <input type="submit" value="Submit" />
            }
            else
            {
                @ViewBag.Answer
            }
        </form>
    </div>
</div>

Web.931803.Chegodaeva.Lab4/Views/Controls/Radio.cshtml
@{
    ViewData["Title"] = "Radio";
}

<div class="row">
    <div class="col-md-3">
        <form asp-action="ControlHandler" asp-controller="Controls">
            <h2>Radio</h2>
            <b>Month</b>

            <input name="type" class="form-control "
                   style="display: none" value="Radio" />

            @if (ViewBag.Visible)
            {
                <p><input name="answer" type="radio" value="January">January</p>
                <p><input name="answer" type="radio" value="February">February</p>
                <p><input name="answer" type="radio" value="March">March</p>
                <p><input name="answer" type="radio" value="April">April</p>
                <p><input name="answer" type="radio" value="May">May</p>
                <p><input name="answer" type="radio" value="June">June</p>
                <p><input name="answer" type="radio" value="July">July</p>
                <p><input name="answer" type="radio" value="August">August</p>
                <p><input name="answer" type="radio" value="September">September</p>
                <p><input name="answer" type="radio" value="October">October</p>
                <p><input name="answer" type="radio" value="November">November</p>
                <p><input name="answer" type="radio" value="December">December</p>
                <br />
                <input type="submit" value="Submit" />
            }
            else
            {
                @ViewBag.Answer
            }
        </form>
    </div>
</div>

Web.931803.Chegodaeva.Lab4/Views/Controls/TextArea.cshtml
@{
    ViewData["Title"] = "Text Area";
}

<div class="row">
    <div class="col-md-3">
        <form asp-action="ControlHandler" asp-controller="Controls">
            <h2>Text Area</h2>
            <b>Text</b>

            <input name="type" class="form-control "
                   style="display: none" value="TextArea" />

            @if (ViewBag.Visible)
            {
                <br />
                <textarea  name="answer"></textarea>
                <br />
                <input type="submit" value="Submit" />
            }
            else
            {
                @ViewBag.Answer
            }
        </form>
    </div>
</div>

Web.931803.Chegodaeva.Lab4/Views/Controls/TextBox.cshtml
@{
    ViewData["Title"] = "Text Box";
}

<div class="row">
    <div class="col-md-3">
        <form asp-action="ControlHandler" asp-controller="Controls">
            <h2>Text Box</h2>
            <b>Text</b>

            <input name="type" class="form-control "
                   style="display: none" value="TextBox"/>

            @if (ViewBag.Visible)
            {
                <input name="answer" class="form-control" />
                <br />
                <input type="submit" value="Submit" />
            }
            else
            {
                @ViewBag.Answer
            }
        </form>
    </div>
</div>

Web.931803.Chegodaeva.Lab4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1>Tools</h1>

    <ul>
        <li>
            <a asp-area="" asp-controller="Controls" asp-action="Index">Controls</a>
        </li>
        <li>
            <a asp-area="" asp-controller="SignUp" asp-action="Index">Multi-staged forms</a>
        </li>
    </ul>
</div>

Web.931803.Chegodaeva.Lab4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend 4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  border-bottom box-shadow mb-3" style="background-color:#222222">
            <div class="container">
                <a class="navbar-brand text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Backend 4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Mockups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white-50" asp-area="" asp-controller="Controls" asp-action="Index">Controls</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Backend 4
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web.931803.Chegodaeva.Lab4/Views/SignUp/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    
}

<div class="text-left">
    <h1>Multi-staged forms</h1>

    <ul>
        <li>
            <a asp-area="" asp-controller="SignUp" asp-action="ResetPassFirst">Password Reset</a>
        </li>
        <li>
            <a asp-area="" asp-controller="SignUp" asp-action="SignUpFirst">Sign Up</a>
        </li>
    </ul>


</div>

Web.931803.Chegodaeva.Lab4/Views/SignUp/ResetPassFirst.cshtml
@model Web._931803.Chegodaeva.Lab4.Models.ResetModel
@{ ViewData["Title"] = "Reset your password"; }

<h2>Reset your password</h2>

<form method="post">
    <label><b>Email</b></label><br />
    @Html.EditorFor(model => model.Email)<br />
    @Html.ValidationMessageFor(model => model.Email)<br />
    <br />
    <div style="display:flex">
        <button class="btn btn-primary col-md-auto" style="display: inline" type="submit" name="action" value="Send">Send me a code</button><br />
        <button class="btn btn-light col-md-auto" style="display: inline; margin-left:10px" type="submit" name="action" value="NoSend">I have a code</button>
    </div>

</form>

Web.931803.Chegodaeva.Lab4/Views/SignUp/ResetPassResult.cshtml
@{
    ViewData["Title"] = "Reset your password";
}

<h3><b>Done</b></h3>

Web.931803.Chegodaeva.Lab4/Views/SignUp/ResetPassSecond.cshtml
@model Web._931803.Chegodaeva.Lab4.Models.ResetModel
@{ ViewData["Title"] = "Reset your password"; }

<h2>Reset your password</h2>
@Model.Message
<form method="post">
    <label><b>Code</b></label><br />
    <input type="text" name="Code" /><br />
    <br />
    <input class="btn btn-light col-md-auto" style="display: inline" type="submit" value="Verify" />
</form>

Web.931803.Chegodaeva.Lab4/Views/SignUp/SignUpFirst.cshtml
@model Web._931803.Chegodaeva.Lab4.Models.SignUpModel
@{ ViewData["Title"] = "Sign Up"; }

<h1>Sign Up</h1>

<form method="post">
    <label><b>First name</b></label><br />
    @Html.EditorFor(model => model.FirstName)<br />
    @Html.ValidationMessageFor(model => model.FirstName)<br />
    <label><b>Last name</b></label><br />
    <input type="text" name="Lastname" /><br />
    <label><b>Birthday</b></label><br />
    <select name="Day">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
        <option value="11">11</option>
        <option value="12">12</option>
        <option value="13">13</option>
        <option value="14">14</option>
        <option value="15">15</option>
        <option value="16">16</option>
        <option value="17">17</option>
        <option value="18">18</option>
        <option value="19">19</option>
        <option value="20">20</option>
        <option value="21">21</option>
        <option value="22">22</option>
        <option value="23">23</option>
        <option value="24">24</option>
        <option value="25">25</option>
        <option value="26">26</option>
        <option value="27">27</option>
        <option value="28">28</option>
        <option value="29">29</option>
        <option value="30">30</option>
        <option value="31">31</option>
    </select>
    <select name="Month">
        <option value="January">January</option>
        <option value="February">February</option>
        <option value="March">March</option>
        <option value="April">April</option>
        <option value="May">May</option>
        <option value="June">June</option>
        <option value="July">July</option>
        <option value="August">August</option>
        <option value="September">September</option>
        <option value="October">October</option>
        <option value="November">November</option>
        <option value="December">December</option>
    </select>
    <select name="Year">
        <option value="1980">1980</option>
        <option value="1981">1981</option>
        <option value="1982">1982</option>
        <option value="1983">1983</option>
        <option value="1984">1984</option>
        <option value="1985">1985</option>
        <option value="1986">1986</option>
        <option value="1987">1987</option>
        <option value="1988">1988</option>
        <option value="1989">1989</option>
        <option value="1990">1990</option>
        <option value="1991">1991</option>
        <option value="1992">1992</option>
        <option value="1993">1993</option>
        <option value="1994">1994</option>
        <option value="1995">1995</option>
        <option value="1996">1996</option>
        <option value="1997">1997</option>
        <option value="1998">1998</option>
        <option value="1999">1999</option>
        <option value="2000">2000</option>
        <option value="2001">2001</option>
        <option value="2002">2002</option>
        <option value="2003">2003</option>
        <option value="2004">2004</option>
        <option value="2005">2005</option>
        <option value="2006">2006</option>
        <option value="2007">2007</option>
    </select><br />
    <label><b>Gender</b></label><br />
    <input type="radio" name="Gender" value="Male" />
    <span>Male</span><br />
    <input type="radio" name="Gender" value="Female" />
    <span>Female</span><br />
    <br />
    <input class="btn btn-primary col-md-auto" style="display: inline" type="submit" value="Sign up" />
</form>

Web.931803.Chegodaeva.Lab4/Views/SignUp/SignUpResult.cshtml
@model Web._931803.Chegodaeva.Lab4.Models.SignUpModel
@{ ViewData["Title"] = "Sign Up"; }

<h1>Sign Up result</h1>

<p>@Model.FirstName</p>
<p>@Model.LastName</p>
<p>@Model.Gender</p>
<p>@Model.Day @Model.Month  @Model.Year</p>
<p>@Model.Email</p>
<p>@Model.Password</p>

Web.931803.Chegodaeva.Lab4/Views/SignUp/SignUpSecond.cshtml
@model Web._931803.Chegodaeva.Lab4.Models.SignUpModel
@{ ViewData["Title"] = "Sign Up"; }

<h1>Sign Up</h1>
<form method="post">
    <input type="hidden" asp-for="FirstName" />
    <input type="hidden" asp-for="LastName" />
    <input type="hidden" asp-for="Gender" />
    <input type="hidden" asp-for="Day" />
    <input type="hidden" asp-for="Month" />
    <input type="hidden" asp-for="Year" />

    <label><b>Email</b></label><br />
    @Html.EditorFor(model => model.Email)<br />
    @Html.ValidationMessageFor(model => model.Email)<br />
    <label><b>Password</b></label><br />
    @Html.EditorFor(model => model.Password)<br />
    @Html.ValidationMessageFor(model => model.Password)<br />
    <label><b>Confirm password</b></label><br />
    @Html.EditorFor(model => model.Confirm)<br />
    @Html.ValidationMessageFor(model => model.Confirm)<br />
    <input type="checkbox" name="Remember" value="true" /><label> Remember?</label><br /><br />
    <input class="btn btn-primary col-md-auto" style="display: inline" type="submit" value="Complete sign up" />
</form>